# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compass < Formula
  desc "Metadata Discovery and Lineage Service"
  homepage "https://github.com/goto/compass"
  version "0.7.5"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goto/compass/releases/download/v0.7.5/compass_Darwin_x86_64.tar.gz"
      sha256 "f51f902a310cd8373952daf043a552eec41bf7a68f30129d4b3d51fcdcd35e83"

      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goto/compass/releases/download/v0.7.5/compass_Darwin_arm64.tar.gz"
      sha256 "9b82a19bd1d50c425378c5ebfb7597282236da741ae09cb8534631a49393e836"

      def install
        bin.install "compass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goto/compass/releases/download/v0.7.5/compass_Linux_x86_64.tar.gz"
      sha256 "55fb622cd62c05c0e83aacf0a7f377f771fb946cf5125041841e99d35131ce9b"

      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goto/compass/releases/download/v0.7.5/compass_Linux_arm.tar.gz"
      sha256 "e688a8979a53f7f2a6a774d8ce60ba5b165f013c5c8daa4ee595bd92c49192e8"

      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goto/compass/releases/download/v0.7.5/compass_Linux_arm64.tar.gz"
      sha256 "f5438ca399a13de4b025ddbaef43b12669246e88018090511fd7b6b6d7ddb74a"

      def install
        bin.install "compass"
      end
    end
  end
end
