# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dex < Formula
  desc "Infrastructure orchestration tool."
  homepage "https://github.com/goto/dex"
  version "0.5.0"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/goto/dex/releases/download/v0.5.0/dex_0.5.0_macos_arm64.tar.gz"
      sha256 "15f0f2db65bf4e7cdcc02f15d121e25ea5f1b44935409b1eb92a33067a55d5d0"

      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goto/dex/releases/download/v0.5.0/dex_0.5.0_macos_x86_64.tar.gz"
      sha256 "9e8e14ddf2ed8908559a4d6e3176e8ec83cb1e3f814a1a61d285de816964fd5b"

      def install
        bin.install "dex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goto/dex/releases/download/v0.5.0/dex_0.5.0_linux_arm64.tar.gz"
      sha256 "88b61793a72ee16101b9829c5bc095b71638c06ba9458bf5f6eeec5e762c8b4e"

      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goto/dex/releases/download/v0.5.0/dex_0.5.0_linux_x86_64.tar.gz"
      sha256 "32090230af783eeddc73231151d7c3646eaad97def33b9bb74a35e387af8bb31"

      def install
        bin.install "dex"
      end
    end
  end
end
