# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entropy < Formula
  desc "Infrastructure orchestration tool."
  homepage "https://github.com/goto/entropy"
  version "0.2.12-rc"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/goto/entropy/releases/download/v0.2.12-rc/entropy_0.2.12-rc_macos_arm64.tar.gz"
      sha256 "38c15d06393c4409d60bb8b58ca4396f0117e0095645eae6ea8cbce1d6f465e1"

      def install
        bin.install "entropy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goto/entropy/releases/download/v0.2.12-rc/entropy_0.2.12-rc_macos_x86_64.tar.gz"
      sha256 "dcd6cdf8adbd76b55e244d8c5bbeb207231d8938ca769a31e7619ef4d173f34d"

      def install
        bin.install "entropy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goto/entropy/releases/download/v0.2.12-rc/entropy_0.2.12-rc_linux_arm64.tar.gz"
      sha256 "d15257be4c32fee3d032d9a44c53f21d9450ee818ec7fa0b929d1fdca3efef28"

      def install
        bin.install "entropy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goto/entropy/releases/download/v0.2.12-rc/entropy_0.2.12-rc_linux_x86_64.tar.gz"
      sha256 "c7cb5f2d54186b111a8c2ad86f631bb2222dc52eac27ae968a8b06429317e6e3"

      def install
        bin.install "entropy"
      end
    end
  end
end
