# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entropy < Formula
  desc "Infrastructure orchestration tool."
  homepage "https://github.com/goto/entropy"
  version "0.3.22-rc3"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/goto/entropy/releases/download/v0.3.22-rc3/entropy_0.3.22-rc3_macos_arm64.tar.gz"
      sha256 "d64428a9bc762ac3f55ba5e6a35302702967108efca1da22a69e3f1e8b5dff38"

      def install
        bin.install "entropy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goto/entropy/releases/download/v0.3.22-rc3/entropy_0.3.22-rc3_macos_x86_64.tar.gz"
      sha256 "8793e9cac96b03abb7dd5eabd205e15d9a7d2a17738c870dab21eb797384a6ce"

      def install
        bin.install "entropy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goto/entropy/releases/download/v0.3.22-rc3/entropy_0.3.22-rc3_linux_arm64.tar.gz"
      sha256 "83a90b0b17ab93ddf4a8b5d16504d9f26571d427d19f1aeecbafd7c6d0f78ad4"

      def install
        bin.install "entropy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goto/entropy/releases/download/v0.3.22-rc3/entropy_0.3.22-rc3_linux_x86_64.tar.gz"
      sha256 "f4debdc22d220d411977e9193b710d6ade8b981296810b8d0ecf89f5ada1060d"

      def install
        bin.install "entropy"
      end
    end
  end
end
