# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guardian < Formula
  desc "Universal data access tool"
  homepage "https://github.com/goto/guardian"
  version "0.12.16-alpha.2"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/goto/guardian/releases/download/v0.12.16-alpha.2/guardian_0.12.16-alpha.2_Darwin_x86_64.tar.gz"
      sha256 "ce374e4c1706e575e645bdafba9ade1d4853ae2b22fc155857571538336c9b19"

      def install
        bin.install "guardian"
      end
    end
    on_arm do
      url "https://github.com/goto/guardian/releases/download/v0.12.16-alpha.2/guardian_0.12.16-alpha.2_Darwin_arm64.tar.gz"
      sha256 "597159a065f2531457662e3f1ad3f86ecd03f5792b13de256436964341e0b56f"

      def install
        bin.install "guardian"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/guardian/releases/download/v0.12.16-alpha.2/guardian_0.12.16-alpha.2_Linux_x86_64.tar.gz"
        sha256 "6c637a7187e7fcc2aafd7277dd007e61a8d2cc83a4e7857d3fa3db2221c7d4cb"

        def install
          bin.install "guardian"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/goto/guardian/releases/download/v0.12.16-alpha.2/guardian_0.12.16-alpha.2_Linux_arm.tar.gz"
        sha256 "89fb65644d9a1488a11669eaf17626c89843e65f121310e6de77f50047c6c5d7"

        def install
          bin.install "guardian"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/guardian/releases/download/v0.12.16-alpha.2/guardian_0.12.16-alpha.2_Linux_arm64.tar.gz"
        sha256 "a3533b7d33b1f9b7e89878ce619bba662fff0e9c3fac4c7d957b9de9a2630437"

        def install
          bin.install "guardian"
        end
      end
    end
  end
end
