# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guardian < Formula
  desc "Universal data access tool"
  homepage "https://github.com/goto/guardian"
  version "0.12.15-alpha.40"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/goto/guardian/releases/download/v0.12.15-alpha.40/guardian_0.12.15-alpha.40_Darwin_x86_64.tar.gz"
      sha256 "6e1738dc257f463016893524a0db1e9e65ad0a92d7c6f0c0e176aed47f426557"

      def install
        bin.install "guardian"
      end
    end
    on_arm do
      url "https://github.com/goto/guardian/releases/download/v0.12.15-alpha.40/guardian_0.12.15-alpha.40_Darwin_arm64.tar.gz"
      sha256 "593d7446000dba2374b65b0c0f6b341694b96eff99e8f6f37dfeefa5e0728672"

      def install
        bin.install "guardian"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/guardian/releases/download/v0.12.15-alpha.40/guardian_0.12.15-alpha.40_Linux_x86_64.tar.gz"
        sha256 "52dbcf95cfea6177d224c32ef5ae1dd1f2494b4e621c814fd68bd944fdd7b1d2"

        def install
          bin.install "guardian"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/goto/guardian/releases/download/v0.12.15-alpha.40/guardian_0.12.15-alpha.40_Linux_arm.tar.gz"
        sha256 "53335ae08c6cbcd4bf3c6704f4ba317f4b7f5168332605d544762964aee6b1cc"

        def install
          bin.install "guardian"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/guardian/releases/download/v0.12.15-alpha.40/guardian_0.12.15-alpha.40_Linux_arm64.tar.gz"
        sha256 "b1c4796469435af21966b2797a38d5de970237ba73e3c31cddf1d007a16c05cd"

        def install
          bin.install "guardian"
        end
      end
    end
  end
end
