# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IapAuth < Formula
  desc "Accessing service behind IAP."
  homepage "https://github.com/goto/iap_auth"
  version "0.0.0"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    url "https://github.com/goto/iap_auth/releases/download/v0.0.0/iap_auth_Darwin_x86_64.tar.gz"
    sha256 "3dd924a1c77e4cbbf607b875c7b4d7e8a31a06157755bb1bc94e1abee275477b"

    def install
      bin.install "iap_auth"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the IapAuth
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goto/iap_auth/releases/download/v0.0.0/iap_auth_Linux_x86_64.tar.gz"
      sha256 "77c1a40ceb9276ceabf87963a0c753ea647cc60fba4a038ca659d4eb451a0a70"

      def install
        bin.install "iap_auth"
      end
    end
  end
end
