# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meteor < Formula
  desc "Metadata collection tool."
  homepage "https://github.com/goto/meteor"
  version "0.11.13"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/goto/meteor/releases/download/v0.11.13/meteor_Darwin_x86_64.tar.gz"
      sha256 "e8a47207fe0f71079f4a52abc1d7e4f1153fd5ee2c1809a16eccbc4a9d6cd824"

      def install
        bin.install "meteor"
      end
    end
    on_arm do
      url "https://github.com/goto/meteor/releases/download/v0.11.13/meteor_Darwin_arm64.tar.gz"
      sha256 "8e786ff54f1916313386ae198e0075175c00e35f135c48cbd04b6e013d5fb1b9"

      def install
        bin.install "meteor"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/meteor/releases/download/v0.11.13/meteor_Linux_x86_64.tar.gz"
        sha256 "79021faf07612581109d5253f0118592c1fad0d1c02ec061f485100c2c276854"

        def install
          bin.install "meteor"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/meteor/releases/download/v0.11.13/meteor_Linux_arm64.tar.gz"
        sha256 "cd4129c0640ba980b31129ebf349e74a3d7bad07a7001fbcb650cccdaca94f98"

        def install
          bin.install "meteor"
        end
      end
    end
  end
end
