# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shield < Formula
  desc "Identity and authorization system"
  homepage "https://github.com/goto/shield"
  version "0.6.23"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/goto/shield/releases/download/v0.6.23/shield_Darwin_x86_64.tar.gz"
      sha256 "2ff57c32c756a5c0a6da955167ec458bdb33cfdf2c28520a8bf39d775ee98149"

      def install
        bin.install "shield"
      end
    end
    on_arm do
      url "https://github.com/goto/shield/releases/download/v0.6.23/shield_Darwin_arm64.tar.gz"
      sha256 "c08ce6073dab1c6fb65ffaf1051e7b14d15d1cf40190e134f9e3c61bc4f1135f"

      def install
        bin.install "shield"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/shield/releases/download/v0.6.23/shield_Linux_x86_64.tar.gz"
        sha256 "89f8f858d0111ab674250161402356331336269b9aacad3e0bd7a1dd435905ab"

        def install
          bin.install "shield"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/goto/shield/releases/download/v0.6.23/shield_Linux_arm.tar.gz"
        sha256 "73bce269f75d0dd705ec7b6fefed6430431b5281b72ceca229be4459b4304184"

        def install
          bin.install "shield"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/shield/releases/download/v0.6.23/shield_Linux_arm64.tar.gz"
        sha256 "973837f144783bbcb889c445843f68920c253cb07a26bf9f8f2fd795892922a1"

        def install
          bin.install "shield"
        end
      end
    end
  end
end
