# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shield < Formula
  desc "Identity and authorization system"
  homepage "https://github.com/goto/shield"
  version "0.7.6-beta-02"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/goto/shield/releases/download/v0.7.6-beta-02/shield_Darwin_x86_64.tar.gz"
      sha256 "a695cbe6289f245096af9881c1a059c01d85e976dccac0f17892ee6c249f0aca"

      def install
        bin.install "shield"
      end
    end
    on_arm do
      url "https://github.com/goto/shield/releases/download/v0.7.6-beta-02/shield_Darwin_arm64.tar.gz"
      sha256 "9451b77e63748b5442deb6c1db00ccd93e63adf315b0ae2d8d2762fbdd96a9f0"

      def install
        bin.install "shield"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/shield/releases/download/v0.7.6-beta-02/shield_Linux_x86_64.tar.gz"
        sha256 "403e64321154f1babb68ee6f642ccde68e90879b156c4f3600cd03174d124a28"

        def install
          bin.install "shield"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/goto/shield/releases/download/v0.7.6-beta-02/shield_Linux_arm.tar.gz"
        sha256 "0b2ec8bfd4e37229ba33afefd14b62571f86c9dc1117a0db04b933fc8ab5f8b7"

        def install
          bin.install "shield"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/shield/releases/download/v0.7.6-beta-02/shield_Linux_arm64.tar.gz"
        sha256 "ba84249348ea09bacb9fe1bd4fd53ce340b3929a409e4dc0328e272831ec98f9"

        def install
          bin.install "shield"
        end
      end
    end
  end
end
