# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirenCortex < Formula
  desc "Cortex plugin for siren."
  homepage "https://github.com/goto/siren/plugins/providers/cortex"
  version "0.6.9"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    url "https://github.com/goto/siren/releases/download/v0.6.9/siren-cortex_Darwin_x86_64.tar.gz"
    sha256 "ce8f0087c48a1375354a5ade92337be0c94b35342f018d4c14b5b815ff7d434b"

    def install
      bin.install "siren-cortex"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the SirenCortex
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goto/siren/releases/download/v0.6.9/siren-cortex_Linux_x86_64.tar.gz"
      sha256 "49f6dfaadb90765108f9a4dbc45a315eba28a1ce5a3e4b43d9ef37092b78a3c6"

      def install
        bin.install "siren-cortex"
      end
    end
  end
end
