# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Siren < Formula
  desc "Universal data observability tool."
  homepage "https://github.com/goto/siren"
  version "0.6.12"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    url "https://github.com/goto/siren/releases/download/v0.6.12/siren_Darwin_x86_64.tar.gz"
    sha256 "a54edc94145ff88e1a3e36ab3bcc2f7cd3345b6c0be0616b1ecd75f6944eeb8e"

    def install
      bin.install "siren"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Siren
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goto/siren/releases/download/v0.6.12/siren_Linux_x86_64.tar.gz"
      sha256 "4f4c79acf303fc0b23660724326fe6bbb232fc82d681cd922de1f485fb73f910"

      def install
        bin.install "siren"
      end
    end
  end
end
