# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirenCortex < Formula
  desc "Cortex plugin for siren."
  homepage "https://github.com/goto/siren/plugins/providers/cortex"
  version "0.6.9-dev"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    url "https://github.com/goto/siren/releases/download/v0.6.9-dev/siren-cortex_Darwin_x86_64.tar.gz"
    sha256 "2ee77ce1631aaa722b9da13eabf9263498ec9a5e16465f09893aee34f2a48b4e"

    def install
      bin.install "siren-cortex"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the SirenCortex
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goto/siren/releases/download/v0.6.9-dev/siren-cortex_Linux_x86_64.tar.gz"
      sha256 "727b6c9b234c6523555f83787157642177aa6aa4749387af9eb8803b1cf30be4"

      def install
        bin.install "siren-cortex"
      end
    end
  end
end
