# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirenCortex < Formula
  desc "Cortex plugin for siren."
  homepage "https://github.com/goto/siren/plugins/providers/cortex"
  version "0.0.1-cortex"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    url "https://github.com/goto/siren/releases/download/v0.0.1-cortex/siren-cortex_Darwin_x86_64.tar.gz"
    sha256 "d46833ddd1c479fea8961e675eba970c6afe8d260dde8d3f86f1337bd3dbfa60"

    def install
      bin.install "siren-cortex"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the SirenCortex
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goto/siren/releases/download/v0.0.1-cortex/siren-cortex_Linux_x86_64.tar.gz"
      sha256 "aa2a32beb0863154f77e6d14cf4b2054378dfcda5b672a0922cb2615e676be95"

      def install
        bin.install "siren-cortex"
      end
    end
  end
end
