# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stencil < Formula
  desc "Schema registry"
  homepage "https://github.com/goto/stencil"
  version "0.8.6"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/goto/stencil/releases/download/v0.8.6/stencil_Darwin_x86_64'.tar.gz"
      sha256 "c338bfe5f582273f6f3587dfb93c95e526466cef931f2b579aaa4484753d2e03"

      def install
        bin.install "stencil"
      end
    end
    on_arm do
      url "https://github.com/goto/stencil/releases/download/v0.8.6/stencil_Darwin_arm64'.tar.gz"
      sha256 "5ece5ea357801959a3456d4b7d760131a76fc35272a0c55bb8660a09ad7ff393"

      def install
        bin.install "stencil"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/stencil/releases/download/v0.8.6/stencil_Linux_x86_64'.tar.gz"
        sha256 "4e412d1acfd87ee3b1fb0cb0d8b375e85fd41ffd97786f1f9d58d87e34a95af2"

        def install
          bin.install "stencil"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/goto/stencil/releases/download/v0.8.6/stencil_Linux_armv6'.tar.gz"
        sha256 "4fb5a724b6faa6b58d144293491eaa99a1e4784e75795d12a1a889c70c6b5d50"

        def install
          bin.install "stencil"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goto/stencil/releases/download/v0.8.6/stencil_Linux_arm64'.tar.gz"
        sha256 "affa72d9015123101b563bee2c8757ddd05b5f328f75b519502613837342698b"

        def install
          bin.install "stencil"
        end
      end
    end
  end
end
